/* Copyright Human Aspects of Software Engineering Lab (HASEL), Department of Informatics, University of Zurich - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Remy Egloff <remy.egloff@uzh.ch>, April 2023
 */

export type UsageDataEvent =
  | 'start'
  | 'quit'
  | 'lock-screen'
  | 'unlock-screen'
  | 'open-snapshot-window'
  | 'close-snapshot-window'
  | 'minimize-snapshot-window'
  | 'restore-snapshot-window'
  | 'focus-snapshot-window'
  | 'blur-snapshot-window'
  | 'open-instant-curation-window'
  | 'close-instant-curation-window'
  | 'minimize-instant-curation-window'
  | 'restore-instant-curation-window'
  | 'focus-instant-curation-window'
  | 'blur-instant-curation-window'
  | 'open-snapshot-gallery-window'
  | 'close-snapshot-gallery-window'
  | 'minimize-snapshot-gallery-window'
  | 'restore-snapshot-gallery-window'
  | 'focus-snapshot-gallery-window'
  | 'blur-snapshot-gallery-window'
  | 'open-mental-context-window'
  | 'close-mental-context-window'
  | 'minimize-mental-context-window'
  | 'restore-mental-context-window'
  | 'focus-mental-context-window'
  | 'blur-mental-context-window'
  | 'open-end-of-day-window'
  | 'close-end-of-day-window'
  | 'minimize-end-of-day-window'
  | 'restore-end-of-day-window'
  | 'focus-end-of-day-window'
  | 'blur-end-of-day-window'
  | 'open-task-resumption-window'
  | 'close-task-resumption-window'
  | 'minimize-task-resumption-window'
  | 'restore-task-resumption-window'
  | 'focus-task-resumption-window'
  | 'blur-task-resumption-window'
  | 'open-settings-window'
  | 'close-settings-window'
  | 'minimize-settings-window'
  | 'restore-settings-window'
  | 'focus-settings-window'
  | 'blur-settings-window'
  | 'create-snapshot'
  | 'create-task'
  | 'start-task'
  | 'commit-task-artefacts'
  | 'restore-snapshot'
  | 'postpone-snapshot'
  | 'open-artifact'
  | 'open-browser-tab'
  | 'open-ide-file'
  | 'open-snapshot'
  | 'delete-snapshot'
  | 'expand-snapshot-preview'
  | 'save-snapshot'
  | 'save-snapshot-and-close-applications'
  | 'connect-supported-usb-device'
  | 'disconnect-supported-usb-device'
  | 'update-known-application'
  | 'add-never-close-tab'
  | 'remove-never-close-tab'
  | 'update-settings'
  | 'merge-snapshots'
  | 'postpone-end-of-day-questionnaire'
  | 'active-study-phase';
